apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: "{{  .Chart.Name }}-application-ingress"
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        backend:
          serviceName: "{{  .Chart.Name }}-application-service"
          servicePort: {{ .Values.service.servicePort }}
